export const eventListArr = [
    "Sporting Event (e.g., professional game, tournament)",
    "Football Game",
    "Baseball Game",
    "Hockey Game",
    "Basketball Game",
    "Soccer Game",
    "Golf",
    "Wedding",
    "Conference (professional or academic)",
    "Vacation (leisure travel)",
    "Festival (music, art, food)",
    "Concert",
    "Family Reunion",
    "Religious Pilgrimage/Event",
    "Business Meeting/Retreat",
    "Funeral/Memorial Service",
    "Educational Workshop/Seminar",
    "Holiday (visiting family/friends)",
    "Trade Show/Exhibition",
    "Theater/Performance (e.g., Broadway show)",
    "Gaming Tournament/Event",
    "Hiking/Camping Trip",
    "Cruise",
    "Destination Wedding/Honeymoon",
    "Retreat (wellness, yoga, etc.)",
    "Charity Event/Fundraiser"
];